name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy NodeJS app
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{ secrets.SERVER_PASSPHRASE }}
      
        script: |
          mkdir Vova
          cd Vova
          touch helper.txt
          git clone https://github.com/guliermo64563/cicd.git
